name: Lint and test
on: [push]
jobs:
  test_and_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up uv
        # Install a specific uv version using the installer
        run: curl -LsSf https://astral.sh/uv/0.3.0/install.sh | sh
      - uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version-file: "pyproject.toml"
          cache: "pip"
      - name: Install the project
        run: uv sync --all-extras --dev
      - name: Cache Pre-commit for format checking
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-3|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
      # pre-commit is now in the virtualenv so can run below
      - name: Check formatting
        run: SKIP=pytest uv run pre-commit run --all-files --show-diff-on-failure
      - name: Run Pytest
        run: uv run pytest
