name: Lint and test
on: [push]
jobs:
  test_and_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: "3.11"
          cache: "pip"
      - uses: yezz123/setup-uv@v3
        id: setup-uv
        with:
          uv-venv: "ci"
      - name: Install dependencies using uv pip
        run: uv pip install -r requirements-dev.lock
      - name: Cache Pre-commit for format checking
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-3|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
      # pre-commit is now in the virtualenv so can run below
      - name: Check formatting
        run: SKIP=pytest pre-commit run --all-files --show-diff-on-failure
      - name: Run Pytest
        run: pytest
