name: Lint and test
on: [push]
jobs:
  test_and_lint:
    runs-on: ubuntu-latest

    env:
      # Configure a constant location for the uv cache
      UV_CACHE_DIR: /tmp/.uv-cache

    steps:
      - uses: actions/checkout@v4
      - name: Set up uv
        # Install a specific uv version using the installer
        run: curl -LsSf https://astral.sh/uv/0.3.0/install.sh | sh

      - uses: actions/setup-python@v6
        id: setup-python
        with:
          python-version-file: "pyproject.toml"
          cache: "pip"

      - name: Restore uv cache
        uses: actions/cache@v4
        with:
          path: /tmp/.uv-cache
          key: uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
            uv-${{ runner.os }}

      - name: Cache Pre-commit for format checking
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-3|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Check formatting
        run: SKIP=pytest uv run pre-commit run --all-files --show-diff-on-failure

      - name: Run Pytest
        run: uv run pytest

      - name: Minimize uv cache
        run: uv cache prune --ci
